version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "pip"
    directory: "/parser"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "pip"
    directory: "/generator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  
  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "docker"
    directory: "/parser"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "docker"
    directory: "/generator"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"