apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netdocgen

resources:
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus.yaml
  - grafana.yaml
  - grafana-dashboard-netdocgen.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: netdocgen-monitoring