apiVersion: v1
kind: ConfigMap
metadata:
  name: parser-config
  namespace: netdocgen
  labels:
    app.kubernetes.io/name: parser
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: netdocgen
data:
  RABBITMQ_URL: "amqp://admin:changeme-in-production@rabbitmq:5672"
  MINIO_ENDPOINT: "minio:9000"

---
apiVersion: v1
kind: Secret
metadata:
  name: parser-secret
  namespace: netdocgen
  labels:
    app.kubernetes.io/name: parser
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: netdocgen
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "changeme-in-production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: netdocgen
  labels:
    app.kubernetes.io/name: parser
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: netdocgen
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: parser
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: parser
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: netdocgen
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for RabbitMQ..."
                sleep 2
              done
      containers:
        - name: parser
          image: ghcr.io/jgiet001-ai/netdocgen-parser:latest
          envFrom:
            - configMapRef:
                name: parser-config
            - secretRef:
                name: parser-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"
            initialDelaySeconds: 30
            periodSeconds: 30